/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-31 19:40:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dnavbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<nav class=\"col-md-2 d-none d-md-block sidebar p-3\"\r\n");
      out.write("\tstyle=\"background: #212529; min-height: 100vh; color: white;\">\r\n");
      out.write("\t<h4 class=\"text-center mb-4\">SHOP ADMIN</h4>\r\n");
      out.write("\t<ul class=\"nav flex-column\" id=\"adminSidebar\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage-product\"\r\n");
      out.write("\t\t\t   class=\"nav-link text-white\"> \r\n");
      out.write("\t\t\t   <i class=\"bi bi-box-seam me-2\"></i>Sản phẩm\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-orders\" class=\"nav-link text-white\">\r\n");
      out.write("\t\t\t    <i class=\"bi bi-cart me-2\"></i>Đơn hàng\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage-contacts\"\r\n");
      out.write("\t\t\t   class=\"nav-link text-white\">\r\n");
      out.write("\t\t\t   <i class=\"bi bi-chat-dots me-2\"></i>Tin nhắn\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage-users\"\r\n");
      out.write("\t\t       class=\"nav-link text-white\"> \r\n");
      out.write("\t\t       <i class=\"bi bi-people me-2\"></i>Người dùng\r\n");
      out.write("\t\t    </a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage-reviews\"\r\n");
      out.write("\t\t       class=\"nav-link text-white\">\r\n");
      out.write("\t\t       <i class=\"bi bi-star me-2\"></i>Đánh giá\r\n");
      out.write("\t\t    </a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item mb-2\">\r\n");
      out.write("\t\t\t<hr class=\"bg-secondary\"> \r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"nav-link text-danger\">\r\n");
      out.write("\t\t\t\t<i class=\"bi bi-box-arrow-right me-2\"></i>Đăng xuất\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Style cho mục đang được chọn */\r\n");
      out.write(".nav-link.active-custom {\r\n");
      out.write("\tbackground: #0d6efd !important;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor: white !important;\r\n");
      out.write("}\r\n");
      out.write("/* Hiệu ứng hover cho các mục khác */\r\n");
      out.write(".nav-link:hover {\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.1);\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("    // 1. Lấy URL hiện tại của trình duyệt\r\n");
      out.write("    const currentUrl = window.location.href;\r\n");
      out.write("    \r\n");
      out.write("    // 2. Lấy tất cả các thẻ <a> trong sidebar\r\n");
      out.write("    const navLinks = document.querySelectorAll('#adminSidebar .nav-link');\r\n");
      out.write("\r\n");
      out.write("    navLinks.forEach(link => {\r\n");
      out.write("        // 3. So sánh URL của thẻ <a> với URL hiện tại\r\n");
      out.write("        if (currentUrl.includes(link.getAttribute('href'))) {\r\n");
      out.write("            link.classList.add('active-custom');\r\n");
      out.write("        } else {\r\n");
      out.write("            // Loại bỏ màu xám (text-secondary) để đồng bộ màu trắng, \r\n");
      out.write("            // chỉ những mục không active mới có màu trắng nhẹ\r\n");
      out.write("            link.style.opacity = \"0.7\";\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
