/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-19 18:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Quản lý tin nhắn - Admin</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".sidebar {\r\n");
      out.write("\tbackground: #212529;\r\n");
      out.write("\tmin-height: 100vh;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg-new {\r\n");
      out.write("\tborder-left: 4px solid #0d6efd;\r\n");
      out.write("\tbackground-color: #f8f9fa;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg-read {\r\n");
      out.write("\tborder-left: 4px solid #6c757d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg-replied {\r\n");
      out.write("\tborder-left: 4px solid #198754;\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin-pages/admin-navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<main class=\"col-md-10 ms-sm-auto px-md-4 py-4\">\r\n");
      out.write("\t\t\t\t<div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"bi bi-envelope-paper me-2\"></i>Tin nhắn khách hàng\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"badge bg-primary\">Mới: 5</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"badge bg-success\">Đã trả lời: 12</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-hover mb-0 align-middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead class=\"table-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Trạng thái</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Khách hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Nội dung tóm tắt</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Ngày gửi</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th class=\"text-center\">Thao tác</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"msg-new\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"badge bg-primary\">MỚI</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><strong>Nguyễn Văn B</strong><br> <small>vânb@gmail.com</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"text-truncate d-inline-block\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"max-width: 300px;\">Tôi muốn hỏi về chính sách\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tđổi trả hàng...</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Vừa xong</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-dark\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-bs-target=\"#viewMessageModal\">Xem & Phản hồi</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"msg-replied\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"badge bg-success\">ĐÃ PHẢN HỒI</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><strong>Trần Thị C</strong><br> <small>0988xxxxxx</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-muted text-truncate d-inline-block\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"max-width: 300px;\">Cảm ơn shop đã tư vấn size\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\táo rất kỹ...</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>1 ngày trước</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-outline-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#viewMessageModal\">Xem\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlại</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"viewMessageModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\">Nội dung tin nhắn</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"fw-bold\">Từ:</label> <span>Nguyễn Văn B\r\n");
      out.write("\t\t\t\t\t\t\t(vânb@gmail.com - 0901234567)</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3 p-3 bg-light rounded border\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0\">\"Chào shop, mình mới mua một chiếc áo sơ mi\r\n");
      out.write("\t\t\t\t\t\t\tnam size L nhưng mặc hơi chật. Shop cho mình hỏi có được hỗ trợ\r\n");
      out.write("\t\t\t\t\t\t\tđổi sang size XL không ạ? Mình cảm ơn.\"</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-label fw-bold\">Trả lời khách hàng:</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Nhập nội dung phản hồi gửi đến email khách hàng...\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"bi bi-send me-1\"></i> Gửi phản hồi\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
