/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-19 18:35:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_002dmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1766080241047L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090221356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Quản lý sản phẩm - Admin</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".sidebar {\r\n");
      out.write("\tbackground: #212529;\r\n");
      out.write("\tmin-height: 100vh;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-form {\r\n");
      out.write("\tposition: sticky;\r\n");
      out.write("\ttop: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin-pages/admin-navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<main class=\"col-md-10 ms-sm-auto px-md-4 py-4\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Danh sách sản phẩm</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group w-50\">\r\n");
      out.write("\t\t\t\t\t\t\t    <input type=\"text\" id=\"searchInput\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t           placeholder=\"Tìm tên sản phẩm (lọc nhanh)...\">\r\n");
      out.write("\t\t\t\t\t\t\t    <button class=\"btn btn-outline-secondary\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t        <i class=\"bi bi-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive bg-white rounded shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-hover align-middle mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Ảnh</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Tên sản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Danh mục</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Giá</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Màu sắc</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th class=\"text-center\">Thao tác</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm card-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header bg-dark text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"mb-0\" id=\"formTitle\">Thêm sản phẩm mới</h5>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/manage-product\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"productId\" id=\"f_id\" value=\"\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label small fw-bold\">Ảnh sản phẩm</label>\r\n");
      out.write("                                        <input type=\"file\" name=\"productImage\" class=\"form-control\" id=\"f_image\" onchange=\"previewImg(this)\">\r\n");
      out.write("                                        <div id=\"imgPreviewContainer\" class=\"mt-2 text-center\" style=\"display:none;\">\r\n");
      out.write("                                            <img id=\"imgPreview\" src=\"\" class=\"img-thumbnail\" style=\"max-height: 150px;\">\r\n");
      out.write("                                            <p class=\"small text-muted mt-1\">Ảnh hiện tại/mới</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label small fw-bold\">Tên sản phẩm</label> \r\n");
      out.write("                                        <input type=\"text\" name=\"productName\" id=\"f_name\" class=\"form-control\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold\">Danh mục\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tchính</label> <select class=\"form-select\" name=\"categoryId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"f_categoryId\" onchange=\"toggleFields(this.value)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">NAM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">NỮ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">TRANG SỨC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold\">Giá (VNĐ)</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"number\" name=\"price\" id=\"f_price\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold\">Màu sắc</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"color\" id=\"f_color\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"fashionFields\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold text-primary\">Loại\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttrang phục</label> <select class=\"form-select\" name=\"typeId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"f_typeId_fashion\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Áo thun</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">Áo sơ mi</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">Áo khoác</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">Quần jean</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">Quần tây/Váy</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold text-primary\">Kích\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcỡ (Size)</label> <select class=\"form-select\" name=\"size\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"f_size\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"S\">S</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"M\">M</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"L\">L</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"XL\">XL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"jewelryFields\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold text-success\">Loại\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttrang sức</label> <select class=\"form-select\" name=\"typeId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"f_typeId_jewelry\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Nhẫn</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">Dây chuyền</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">Vòng tay</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">Lắc tay</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">Bông tai</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\">Đồng hồ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-label small fw-bold text-success\">Đối\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttượng</label> <select class=\"form-select\" name=\"target\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"f_target\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"NAM\">NAM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"NU\">NỮ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"UNISEX\">UNISEX</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <label class=\"form-label small fw-bold text-success\">Chất liệu</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <select name=\"material\" id=\"f_material\" class=\"form-select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"\">-- Chọn chất liệu --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"Vàng\">Vàng</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"Bạc\">Bạc</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"Titan\">Titan</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"Thép không gỉ\">Thép không gỉ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <option value=\"Đá quý\">Đá quý</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <label class=\"form-label small fw-bold\">Mô tả sản phẩm</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <textarea name=\"description\" id=\"f_description\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t              rows=\"3\" placeholder=\"Nhập mô tả ngắn về sản phẩm...\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-grid gap-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" id=\"btnSubmit\">Lưu\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsản phẩm</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-light border\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"resetForm()\">Làm mới</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Hàm xem trước ảnh khi chọn file\r\n");
      out.write("\t    function previewImg(input) {\r\n");
      out.write("\t        if (input.files && input.files[0]) {\r\n");
      out.write("\t            var reader = new FileReader();\r\n");
      out.write("\t            reader.onload = function(e) {\r\n");
      out.write("\t                document.getElementById('imgPreview').src = e.target.result;\r\n");
      out.write("\t                document.getElementById('imgPreviewContainer').style.display = 'block';\r\n");
      out.write("\t            }\r\n");
      out.write("\t            reader.readAsDataURL(input.files[0]);\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\t// Hàm ẩn hiện các trường nhập liệu\r\n");
      out.write("\t\tfunction toggleFields(categoryId) {\r\n");
      out.write("\t\t\tconst fashion = document.getElementById('fashionFields');\r\n");
      out.write("\t\t    const jewelry = document.getElementById('jewelryFields');\r\n");
      out.write("\t\t    const typeFashion = document.getElementById('f_typeId_fashion');\r\n");
      out.write("\t\t    const typeJewelry = document.getElementById('f_typeId_jewelry');\r\n");
      out.write("\t\t    if (categoryId == '3') { // TRANG SỨC\r\n");
      out.write("\t\t        fashion.style.display = 'none';\r\n");
      out.write("\t\t        jewelry.style.display = 'block';\r\n");
      out.write("\t\t        typeFashion.disabled = true;  // Vô hiệu hóa để không gửi lên server\r\n");
      out.write("\t\t        typeJewelry.disabled = false; // Kích hoạt ô trang sức\r\n");
      out.write("\t\t    } else { // NAM hoặc NỮ\r\n");
      out.write("\t\t        fashion.style.display = 'block';\r\n");
      out.write("\t\t        jewelry.style.display = 'none';\r\n");
      out.write("\t\t        typeFashion.disabled = false;\r\n");
      out.write("\t\t        typeJewelry.disabled = true;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Hàm điền dữ liệu vào form khi nhấn \"Sửa\"\r\n");
      out.write("\t\tfunction editProduct(id, name, price, color, catId, typeId, size, target,\r\n");
      out.write("\t\t\t\tmaterial, imageUrl) {\r\n");
      out.write("\t\t\tdocument.getElementById('formTitle').innerText = \"Cập nhật sản phẩm #\"\r\n");
      out.write("\t\t\t\t\t+ id;\r\n");
      out.write("\t\t\tdocument.getElementById('f_id').value = id;\r\n");
      out.write("\t\t\tdocument.getElementById('f_name').value = name;\r\n");
      out.write("\t\t\tdocument.getElementById('f_price').value = price;\r\n");
      out.write("\t\t\tdocument.getElementById('f_color').value = color;\r\n");
      out.write("\t\t\tdocument.getElementById('f_categoryId').value = catId;\r\n");
      out.write("\t\t\tdocument.getElementById('f_description').value = desc !== 'undefined' ? desc : \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttoggleFields(catId);\r\n");
      out.write("\t\t\t// Điền typeId vào đúng ô đang hiển thị\r\n");
      out.write("\t\t    if (catId == '3') {\r\n");
      out.write("\t\t        document.getElementById('f_typeId_jewelry').value = typeId;\r\n");
      out.write("\t\t    } else {\r\n");
      out.write("\t\t        document.getElementById('f_typeId_fashion').value = typeId;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById('f_size').value = size;\r\n");
      out.write("\t\t\tdocument.getElementById('f_target').value = target;\r\n");
      out.write("\t\t\tconst materialSelect = document.getElementById('f_material');\r\n");
      out.write("\t\t\tmaterialSelect.value = material;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t \t// Hiển thị ảnh cũ để biết đang sửa sản phẩm nào\r\n");
      out.write("            if(imageUrl && imageUrl !== 'default.jpg') {\r\n");
      out.write("                document.getElementById('imgPreview').src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/uploaded-images/\" + imageUrl;\r\n");
      out.write("                document.getElementById('imgPreviewContainer').style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById('imgPreviewContainer').style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById('btnSubmit').className = \"btn btn-warning\";\r\n");
      out.write("\t\t\tdocument.getElementById('btnSubmit').innerText = \"Cập nhật sản phẩm\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Hàm reset form về trạng thái \"Thêm mới\"\r\n");
      out.write("\t\tfunction resetForm() {\r\n");
      out.write("\t\t\tdocument.getElementById('formTitle').innerText = \"Thêm sản phẩm mới\";\r\n");
      out.write("\t\t\tdocument.getElementById('f_id').value = \"\";\r\n");
      out.write("\t\t\tdocument.querySelector('form').reset();\r\n");
      out.write("\t\t\tdocument.getElementById('f_description').value = \"\";\r\n");
      out.write("\t\t\t// Ẩn preview ảnh khi reset\r\n");
      out.write("\t\t    document.getElementById('imgPreviewContainer').style.display = 'none';\r\n");
      out.write("\t\t    document.getElementById('imgPreview').src = \"\";\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\ttoggleFields('1');\r\n");
      out.write("\t\t\tdocument.getElementById('btnSubmit').className = \"btn btn-primary\";\r\n");
      out.write("\t\t\tdocument.getElementById('btnSubmit').innerText = \"Lưu sản phẩm\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tdocument.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\t\t    const searchInput = document.getElementById(\"searchInput\");\r\n");
      out.write("\t\t    const tableRows = document.querySelectorAll(\"tbody tr\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t    searchInput.addEventListener(\"keyup\", function () {\r\n");
      out.write("\t\t        const query = searchInput.value.toLowerCase().trim();\r\n");
      out.write("\t\r\n");
      out.write("\t\t        tableRows.forEach((row) => {\r\n");
      out.write("\t\t            // Lấy tên sản phẩm ở cột thứ 3 (index 2) hoặc tùy chỉnh theo thứ tự cột của bạn\r\n");
      out.write("\t\t            const text = row.innerText.toLowerCase();\r\n");
      out.write("\t\r\n");
      out.write("\t\t            if (text.includes(query)) {\r\n");
      out.write("\t\t                row.style.display = \"\"; // Hiện dòng\r\n");
      out.write("\t\t            } else {\r\n");
      out.write("\t\t                row.style.display = \"none\"; // Ẩn dòng\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin-pages/product-manager.jsp(62,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /admin-pages/product-manager.jsp(62,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("                                                <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/assets/uploaded-images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("                                                     alt=\"img\" class=\"rounded\" style=\"width: 50px; height: 50px; object-fit: cover;\">\r\n");
            out.write("                                            </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td><strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("đ</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"text-center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-info text-white\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"editProduct('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.typeId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.target}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.material}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', `");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("`)\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"bi bi-pencil\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</button> <a href=\"manage-product?action=delete&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-sm btn-danger\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"bi bi-trash\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /admin-pages/product-manager.jsp(71,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryId == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-primary\">NAM</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /admin-pages/product-manager.jsp(74,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryId == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-info\">NỮ</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"badge bg-warning text-dark\">TRANG SỨC</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
