/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-31 18:11:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1766754556946L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090221356000L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1090221356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Liên hệ | Fashion Shop</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tmax-width: 1100px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tpadding: 40px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= TITLE ================= */\r\n");
      out.write(".page-title {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title h1 {\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tcolor: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title p {\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= CONTACT WRAPPER ================= */\r\n");
      out.write(".contact-wrapper {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 1fr 1fr;\r\n");
      out.write("\tgap: 30px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("\tbox-shadow: 0 5px 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= INFO ================= */\r\n");
      out.write(".contact-info h3 {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tcolor: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info p {\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-item {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-item i {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tcolor: #3498db;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\twidth: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= FORM ================= */\r\n");
      out.write(".contact-form h3 {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tcolor: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form input, .contact-form textarea {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 12px 15px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form input:focus, .contact-form textarea:focus {\r\n");
      out.write("\tborder-color: #3498db;\r\n");
      out.write("\tbox-shadow: 0 0 0 3px rgba(52, 152, 219, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form textarea {\r\n");
      out.write("\tresize: none;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form button {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 12px;\r\n");
      out.write("\tbackground: #3498db;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 25px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form button:hover {\r\n");
      out.write("\tbackground: #2980b9;\r\n");
      out.write("}\r\n");
      out.write("/* Style cho ô thông báo */\r\n");
      out.write(".alert-box {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 20px;\r\n");
      out.write("\tright: 20px;\r\n");
      out.write("\tmin-width: 300px;\r\n");
      out.write("\tpadding: 15px 20px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tbox-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("\tanimation: slideIn 0.5s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".success {\r\n");
      out.write("\tbackground-color: #2ecc71;\r\n");
      out.write("} /* Màu xanh lá */\r\n");
      out.write(".error {\r\n");
      out.write("\tbackground-color: #e74c3c;\r\n");
      out.write("} /* Màu đỏ */\r\n");
      out.write(".alert-content {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tgap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert-content i {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close-btn {\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/navbar.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- TITLE -->\r\n");
      out.write("\t\t<div class=\"page-title\">\r\n");
      out.write("\t\t\t<h1>Liên hệ với chúng tôi</h1>\r\n");
      out.write("\t\t\t<p>Nếu bạn có thắc mắc hoặc cần hỗ trợ, hãy gửi tin nhắn cho\r\n");
      out.write("\t\t\t\tchúng tôi</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CONTACT CONTENT -->\r\n");
      out.write("\t\t<div class=\"contact-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- INFO -->\r\n");
      out.write("\t\t\t<div class=\"contact-info\">\r\n");
      out.write("\t\t\t\t<h3>Thông tin cửa hàng</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>Fashion Shop – Thời trang nam & nữ, cập nhật xu hướng mới\r\n");
      out.write("\t\t\t\t\tnhất.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"info-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-location-dot\"></i> 123 Nguyễn Văn A, TP. Hồ\r\n");
      out.write("\t\t\t\t\tChí Minh\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"info-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-phone\"></i> 0123 456 789\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"info-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-envelope\"></i> support@fashionshop.com\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"info-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-clock\"></i> 08:00 – 22:00 (T2 – CN)\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- FORM -->\r\n");
      out.write("\t\t\t<div class=\"contact-form\">\r\n");
      out.write("\t\t\t\t<h3>Gửi tin nhắn</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"fullName\" placeholder=\"Họ và tên\" required>\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"phone\" placeholder=\"Số điện thoại\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"message\" placeholder=\"Nội dung liên hệ...\" required></textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-paper-plane\"></i> Gửi liên hệ\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /user-pages/contact.jsp(175,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.success == 'true'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"success-alert\" class=\"alert-box success\">\r\n");
          out.write("\t\t\t<div class=\"alert-content\">\r\n");
          out.write("\t\t\t\t<i class=\"fa-solid fa-circle-check\"></i> <span>Gửi tin nhắn\r\n");
          out.write("\t\t\t\t\tthành công! Chúng tôi sẽ sớm phản hồi bạn.</span>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<button class=\"close-btn\"\r\n");
          out.write("\t\t\t\tonclick=\"this.parentElement.style.display='none'\">&times;</button>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /user-pages/contact.jsp(186,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.error == 'true'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"error-alert\" class=\"alert-box error\">\r\n");
          out.write("\t\t\t<div class=\"alert-content\">\r\n");
          out.write("\t\t\t\t<i class=\"fa-solid fa-circle-exclamation\"></i> <span>Gửi thất\r\n");
          out.write("\t\t\t\t\tbại. Vui lòng kiểm tra lại thông tin!</span>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<button class=\"close-btn\"\r\n");
          out.write("\t\t\t\tonclick=\"this.parentElement.style.display='none'\">&times;</button>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
