/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-18 17:56:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Sự kiện & Thông báo | Fashion Shop</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tmax-width: 1100px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tpadding: 30px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= PAGE TITLE ================= */\r\n");
      out.write(".page-title {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title h1 {\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tcolor: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title p {\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= EVENT LIST ================= */\r\n");
      out.write(".event-list {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: repeat(auto-fill, minmax(320px, 1fr));\r\n");
      out.write("\tgap: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-radius: 14px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbox-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("\ttransition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card:hover {\r\n");
      out.write("\ttransform: translateY(-6px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-img {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-img img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-badge {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 15px;\r\n");
      out.write("\tleft: 15px;\r\n");
      out.write("\tpadding: 6px 14px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sale {\r\n");
      out.write("\tbackground: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new {\r\n");
      out.write("\tbackground: #27ae60;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hot {\r\n");
      out.write("\tbackground: #f39c12;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-content {\r\n");
      out.write("\tpadding: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-content h3 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmargin-bottom: 8px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-content p {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-time {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-btn {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 8px 18px;\r\n");
      out.write("\tbackground: #3498db;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-btn:hover {\r\n");
      out.write("\tbackground: #2980b9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- PAGE TITLE -->\r\n");
      out.write("\t\t<div class=\"page-title\">\r\n");
      out.write("\t\t\t<h1>Thông báo & Sự kiện</h1>\r\n");
      out.write("\t\t\t<p>Cập nhật các chương trình ưu đãi và sản phẩm mới nhất</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- EVENT LIST -->\r\n");
      out.write("\t\t<div class=\"event-list\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- EVENT -->\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/promo.avif\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Sale\"> <span class=\"event-badge sale\">SALE</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>Sale mùa hè lên đến 50%</h3>\r\n");
      out.write("\t\t\t\t\t<p>Ưu đãi cực sốc cho toàn bộ áo thun, quần short và váy hè.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-clock\"></i> 01/06 - 15/06\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"event-btn\">Xem chi tiết</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- EVENT -->\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/promo.avif\"\r\n");
      out.write("\t\t\t\t\t\talt=\"New\"> <span class=\"event-badge new\">NEW</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>Ra mắt bộ sưu tập Thu Đông</h3>\r\n");
      out.write("\t\t\t\t\t<p>Phong cách mới, chất liệu cao cấp dành cho cả nam và nữ.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-calendar\"></i> Từ 20/09\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"event-btn\">Khám phá</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- EVENT -->\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-img\">\r\n");
      out.write("\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/promo.avif\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Hot\"> <span class=\"event-badge hot\">HOT</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>Flash Sale cuối tuần</h3>\r\n");
      out.write("\t\t\t\t\t<p>Giảm giá sốc trong 48 giờ – Số lượng có hạn.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-clock\"></i> Cuối tuần này\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"event-btn\">Mua ngay</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>📦 Đơn hàng đang giao</h3>\r\n");
      out.write("\t\t\t\t\t<p>Đơn hàng #DH1023 của bạn đang trên đường giao đến.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-clock\"></i> 2 giờ trước\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>🆕 Sản phẩm mới</h3>\r\n");
      out.write("\t\t\t\t\t<p>Bộ sưu tập Street Style 2025 đã có mặt tại shop.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-calendar\"></i> Hôm nay\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"event-card\">\r\n");
      out.write("\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("\t\t\t\t\t<h3>💡 Xu hướng tuần này</h3>\r\n");
      out.write("\t\t\t\t\t<p>Áo croptop + quần ống rộng đang là lựa chọn hot.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"event-time\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-regular fa-fire\"></i> Trending\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
