/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-31 18:11:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer {\r\n");
      out.write("\tbackground: #f5f6f8;\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("\tpadding-top: 70px;\r\n");
      out.write("\tborder-top: 1px solid #e0e0e0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("\tmax-width: 1200px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: repeat(4, 1fr);\r\n");
      out.write("\tgap: 40px;\r\n");
      out.write("\tpadding: 0 20px 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* LOGO */\r\n");
      out.write(".footer-logo {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #111;\r\n");
      out.write("\tmargin-bottom: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* TIÊU ĐỀ */\r\n");
      out.write(".footer-col h4 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-bottom: 18px;\r\n");
      out.write("\tcolor: #111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* TEXT */\r\n");
      out.write(".footer-col p {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* LINKS */\r\n");
      out.write(".footer-col ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-col ul li {\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-col ul li a {\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttransition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-col ul li a:hover {\r\n");
      out.write("\tcolor: #111;\r\n");
      out.write("\tpadding-left: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CONTACT ICON */\r\n");
      out.write(".footer-col i {\r\n");
      out.write("\tmargin-right: 8px;\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SOCIAL */\r\n");
      out.write(".social {\r\n");
      out.write("\tmargin-top: 18px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tgap: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social a {\r\n");
      out.write("\twidth: 36px;\r\n");
      out.write("\theight: 36px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("\ttransition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social a:hover {\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-color: #111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* BOTTOM */\r\n");
      out.write(".footer-bottom {\r\n");
      out.write("\tborder-top: 1px solid #e0e0e0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 18px 0;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #888;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- BRAND -->\r\n");
      out.write("\t\t\t<div class=\"footer-col\">\r\n");
      out.write("\t\t\t\t<h3 class=\"footer-logo\">Fashion Store</h3>\r\n");
      out.write("\t\t\t\t<p>Thương hiệu thời trang hiện đại, mang đến phong cách trẻ\r\n");
      out.write("\t\t\t\t\ttrung – thanh lịch – cá tính cho mọi khách hàng.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- QUICK LINKS -->\r\n");
      out.write("\t\t\t<div class=\"footer-col\">\r\n");
      out.write("\t\t\t\t<h4>Liên kết nhanh</h4>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Sản phẩm</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Yêu thích</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Giỏ hàng</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- SUPPORT -->\r\n");
      out.write("\t\t\t<div class=\"footer-col\">\r\n");
      out.write("\t\t\t\t<h4>Hỗ trợ khách hàng</h4>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Chính sách đổi trả</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Hướng dẫn mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Thanh toán</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Câu hỏi thường gặp</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- CONTACT -->\r\n");
      out.write("\t\t\t<div class=\"footer-col\">\r\n");
      out.write("\t\t\t\t<h4>Liên hệ</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-location-dot\"></i> Hà Nội, Việt Nam\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-phone\"></i> 0123 456 789\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-envelope\"></i> support@fashionstore.com\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a> <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-instagram\"></i></a> <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-tiktok\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- COPYRIGHT -->\r\n");
      out.write("\t\t<div class=\"footer-bottom\">© 2025 Fashion Store. All rights\r\n");
      out.write("\t\t\treserved.</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).on('click', '.btn-cart', function(e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    var productId = $(this).attr('data-id'); // Đảm bảo dùng .attr('data-id') hoặc .data('id')\r\n");
      out.write("    \r\n");
      out.write("    if(!productId) {\r\n");
      out.write("        console.error(\"Không tìm thấy ID sản phẩm trên nút này!\");\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        // Dùng đường dẫn tuyệt đối từ gốc project\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart-controller', \r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        data: {\r\n");
      out.write("            action: 'add',\r\n");
      out.write("            pid: productId\r\n");
      out.write("        },\r\n");
      out.write("        // Thêm dòng này để trình duyệt nhận diện đây là yêu cầu Ajax\r\n");
      out.write("        headers: {\r\n");
      out.write("            \"X-Requested-With\": \"XMLHttpRequest\"\r\n");
      out.write("        },\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("            alert('Đã thêm sản phẩm vào giỏ hàng thành công!');\r\n");
      out.write("            // Cập nhật số lượng trên icon giỏ hàng nếu có\r\n");
      out.write("            $('.cart-badge').text(response); \r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr, status, error) {\r\n");
      out.write("            console.error(\"Lỗi chi tiết:\", status, error);\r\n");
      out.write("            if(xhr.status === 401) {\r\n");
      out.write("                alert('Vui lòng đăng nhập để thực hiện chức năng này!');\r\n");
      out.write("                window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user-pages/login.jsp';\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('Có lỗi xảy ra (Mã lỗi: ' + xhr.status + '). Vui lòng thử lại!');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).on('click', '.btn-wishlist', function(e) {\r\n");
      out.write("    var btn = $(this);\r\n");
      out.write("    var productId = btn.data('id');\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/wishlist-controller',\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        data: {\r\n");
      out.write("            action: 'add',\r\n");
      out.write("            pid: productId\r\n");
      out.write("        },\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("            // Hiệu ứng đổi màu trái tim sang đỏ để người dùng biết đã thích thành công\r\n");
      out.write("            btn.find('i').css('color', 'red'); \r\n");
      out.write("            alert('Đã thêm vào danh sách yêu thích!');\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr) {\r\n");
      out.write("            if (xhr.status === 401) {\r\n");
      out.write("                alert('Vui lòng đăng nhập để sử dụng chức năng yêu thích!');\r\n");
      out.write("                window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user-pages/login.jsp';\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('Lỗi: Không thể thêm vào yêu thích.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
