/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-31 18:11:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1766754556946L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090221356000L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1090221356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Fashion Store</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>/* ===== BANNER SLIDER ===== */\r\n");
      out.write(".banner-slider {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 420px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-slide {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-slide img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 420px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* nội dung trên banner */\r\n");
      out.write(".swiper-desc {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 80px;\r\n");
      out.write("\ttransform: translateY(-50%);\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tmax-width: 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-desc h1 {\r\n");
      out.write("\tfont-size: 48px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-desc p {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-btn {\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("\tpadding: 12px 28px;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SECTION */\r\n");
      out.write("section {\r\n");
      out.write("\tpadding: 60px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-title {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-list {\r\n");
      out.write("\tmax-width: 1200px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: repeat(3, 1fr);\r\n");
      out.write("\tgap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-item {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: 18px;\r\n");
      out.write("\tbox-shadow: 0 8px 25px rgba(0, 0, 0, 0.12);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-item img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 280px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\ttransition: transform 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-item span {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 25px;\r\n");
      out.write("\tleft: 25px;\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-item::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tinset: 0;\r\n");
      out.write("\tbackground: linear-gradient(to top, rgba(0, 0, 0, 0.6), transparent);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category-item:hover img {\r\n");
      out.write("\ttransform: scale(1.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".products {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-list {\r\n");
      out.write("\tmax-width: 1200px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: repeat(4, 1fr);\r\n");
      out.write("\tgap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-radius: 16px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbox-shadow: 0 6px 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("\ttransition: all 0.35s ease;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 260px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card h3 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\tmargin: 18px 0 8px;\r\n");
      out.write("\tpadding: 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card .price {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: #e53935;\r\n");
      out.write("\tmargin-bottom: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card:hover {\r\n");
      out.write("\ttransform: translateY(-10px);\r\n");
      out.write("\tbox-shadow: 0 12px 35px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 15px;\r\n");
      out.write("\tleft: 15px;\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tpadding: 5px 12px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wishlist {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 15px;\r\n");
      out.write("\tright: 15px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.4);\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wishlist:hover {\r\n");
      out.write("\tcolor: #e53935;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-actions {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tinset: 0;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.4);\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card:hover .product-actions {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-detail {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 8px 15px;\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-detail:hover {\r\n");
      out.write("    background-color: #555;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-detail i {\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-info {\r\n");
      out.write("\tpadding: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-info h3 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin: 6px 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating {\r\n");
      out.write("\tcolor: #fbc02d;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating span {\r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".colors {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\tgap: 8px;\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".color {\r\n");
      out.write("\twidth: 14px;\r\n");
      out.write("\theight: 14px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".color.black {\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".color.beige {\r\n");
      out.write("\tbackground: #d7c6a1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".color.gray {\r\n");
      out.write("\tbackground: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo {\r\n");
      out.write("\tpadding: 80px 20px;\r\n");
      out.write("\tbackground: #f7f7f7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-box {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmax-width: 1200px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tborder-radius: 24px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbox-shadow: 0 15px 40px rgba(0, 0, 0, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-box img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 420px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\ttransition: transform 0.6s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Overlay tối */\r\n");
      out.write(".promo-box::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tinset: 0;\r\n");
      out.write("\tbackground: linear-gradient(to right, rgba(0, 0, 0, 0.6),\r\n");
      out.write("\t\trgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.05));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nội dung */\r\n");
      out.write(".promo-content {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 70px;\r\n");
      out.write("\ttransform: translateY(-50%);\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\tmax-width: 420px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-tag {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground: #e53935;\r\n");
      out.write("\tpadding: 6px 14px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tmargin-bottom: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-content h2 {\r\n");
      out.write("\tfont-size: 40px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-content p {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-btn {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 12px 30px;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #111;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttransition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".promo-btn:hover {\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hover effect */\r\n");
      out.write(".promo-box:hover img {\r\n");
      out.write("\ttransform: scale(1.08);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"swiper mySwiper banner-slider\">\r\n");
      out.write("\t\t<div class=\"swiper-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/banner4.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"swiper-desc\">\r\n");
      out.write("\t\t\t\t\t<h1>Thời trang hiện đại</h1>\r\n");
      out.write("\t\t\t\t\t<p>Khám phá bộ sưu tập hot nhất 2025</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user-pages/hot.jsp\" class=\"swiper-btn\">Mua ngay</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/banner1.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"swiper-desc\">\r\n");
      out.write("\t\t\t\t\t<h1>Phong cách nam tính</h1>\r\n");
      out.write("\t\t\t\t\t<p>Áo khoác – quần jean – streetwear</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/male-clothes\" class=\"swiper-btn\">Xem ngay</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/banner2.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"swiper-desc\">\r\n");
      out.write("\t\t\t\t\t<h1>Thời trang nữ</h1>\r\n");
      out.write("\t\t\t\t\t<p>Thanh lịch – hiện đại – cá tính</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/female-clothes\" class=\"swiper-btn\">Khám phá</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- dots -->\r\n");
      out.write("\t\t<div class=\"swiper-pagination\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- arrows (tuỳ chọn) -->\r\n");
      out.write("\t\t<div class=\"swiper-button-next\"></div>\r\n");
      out.write("\t\t<div class=\"swiper-button-prev\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"category\">\r\n");
      out.write("\t\t<h2 class=\"section-title\">Danh mục nổi bật</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"category-list\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/male-clothes\"\" class=\"category-item\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Male/Male_adult/ao-vest.jpg\">\r\n");
      out.write("\t\t\t\t<span>Thời trang nam</span>\r\n");
      out.write("\t\t\t</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/female-clothes\" class=\"category-item\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Female/Female_adult/ao-2-day.jpg\">\r\n");
      out.write("\t\t\t\t<span>Thời trang nữ</span>\r\n");
      out.write("\t\t\t</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jewelry\" class=\"category-item\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Female/Trang_suc_nu/bong-tai.jpeg\">\r\n");
      out.write("\t\t\t\t<span>Phụ kiện</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"products\">\r\n");
      out.write("\t    <h2 class=\"section-title\">Sản phẩm nổi bật</h2>\r\n");
      out.write("\t    <div class=\"product-list\">\r\n");
      out.write("\t        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"products\">\r\n");
      out.write("\t    <h2 class=\"section-title\">Sản phẩm mới</h2>\r\n");
      out.write("\t    <div class=\"product-list\">\r\n");
      out.write("\t        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tconst swiper = new Swiper(\".mySwiper\", {\r\n");
      out.write("\t\tloop : true,\r\n");
      out.write("\t\tautoplay : {\r\n");
      out.write("\t\t\tdelay : 5000,\r\n");
      out.write("\t\t\tdisableOnInteraction : false,\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tpagination : {\r\n");
      out.write("\t\t\tel : \".swiper-pagination\",\r\n");
      out.write("\t\t\tclickable : true,\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tnavigation : {\r\n");
      out.write("\t\t\tnextEl : \".swiper-button-next\",\r\n");
      out.write("\t\t\tprevEl : \".swiper-button-prev\",\r\n");
      out.write("\t\t},\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /user-pages/home.jsp(427,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listBest}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/home.jsp(427,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t            <div class=\"product-card\">\r\n");
            out.write("\t                <div class=\"product-image\">\r\n");
            out.write("\t                    ");
            out.write("\r\n");
            out.write("\t                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/assets/uploaded-images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty p.imageUrl ? p.imageUrl : 'banner1.jpg'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t                    <span class=\"badge\" style=\"background: #ff4757;\">HOT</span>\r\n");
            out.write("\t                    <div class=\"product-actions\">\r\n");
            out.write("\t                       <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product-detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn-detail\"> <i class=\"fa fa-eye\"></i> Xem chi tiết</a>\r\n");
            out.write("\t                    </div>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"product-info\">\r\n");
            out.write("\t                    <span class=\"category\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t                    <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("\t                    <p class=\"price\">");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("đ</p>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-pages/home.jsp(440,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/home.jsp(440,38) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /user-pages/home.jsp(450,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listNew}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/home.jsp(450,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t            <div class=\"product-card\">\r\n");
            out.write("\t                <div class=\"product-image\">\r\n");
            out.write("\t                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/assets/uploaded-images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty p.imageUrl ? p.imageUrl : 'default.jpg'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t                    <span class=\"badge\">NEW</span>\r\n");
            out.write("\t                    <div class=\"product-actions\">\r\n");
            out.write("\t                        <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product-detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn-detail\"> <i class=\"fa fa-eye\"></i> Xem chi tiết</a>\r\n");
            out.write("\t                    </div>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"product-info\">\r\n");
            out.write("\t                    <span class=\"category\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t                    <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("\t                    <p class=\"price\">");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("đ</p>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /user-pages/home.jsp(462,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/home.jsp(462,38) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
