/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2025-12-31 18:11:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class male_002dclothe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1766754556946L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090221356000L));
    _jspx_dependants.put("jar:file:/D:/LTWeb/web_ban_quan_ao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Clothes-shop-website/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1090221356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Sản phẩm nam| Fashion Shop</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 250px 1fr;\r\n");
      out.write("\tgap: 20px;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= FAVORITE (HEART) ================= */\r\n");
      out.write(".favorite {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor: #ccc;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".favorite:hover {\r\n");
      out.write("\tbackground: #e74c3c;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttransform: scale(1.15);\r\n");
      out.write("\tbox-shadow: 0 4px 10px rgba(231, 76, 60, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= BUTTON COMMON ================= */\r\n");
      out.write(".btn {\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= ADD TO CART ================= */\r\n");
      out.write(".btn-cart {\r\n");
      out.write("\tbackground: #2ecc71;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-cart:hover {\r\n");
      out.write("\tbackground: #27ae60;\r\n");
      out.write("\ttransform: translateY(-3px);\r\n");
      out.write("\tbox-shadow: 0 5px 15px rgba(46, 204, 113, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= DETAIL BUTTON ================= */\r\n");
      out.write(".btn-detail {\r\n");
      out.write("\tbackground: #3498db;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-detail:hover {\r\n");
      out.write("\tbackground: #2980b9;\r\n");
      out.write("\ttransform: translateY(-3px);\r\n");
      out.write("\tbox-shadow: 0 5px 15px rgba(52, 152, 219, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= FILTER ================= */\r\n");
      out.write(".filter {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filter h3 {\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filter-group {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filter-group label {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= PRODUCTS ================= */\r\n");
      out.write(".products {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".products-header {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".products-grid {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: repeat(auto-fill, minmax(220px, 1fr));\r\n");
      out.write("\tgap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbox-shadow: 0 2px 10px rgba(0, 0, 0, 0.08);\r\n");
      out.write("\ttransition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-img {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-img img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 280px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".favorite {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-info {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-info h4 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("\tcolor: #e67e22;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-group {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tgap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tflex: 1;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-cart {\r\n");
      out.write("\tbackground: #2ecc71;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-detail {\r\n");
      out.write("\tbackground: #3498db;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= PRODUCTS HEADER ================= */\r\n");
      out.write(".products-header {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("\tborder-bottom: 2px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* TITLE */\r\n");
      out.write(".products-header h2 {\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* underline nhẹ cho tiêu đề */\r\n");
      out.write(".products-header h2::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 3px;\r\n");
      out.write("\tbackground: #e67e22;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: -8px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ================= SORT SELECT ================= */\r\n");
      out.write(".products-header select {\r\n");
      out.write("\tpadding: 8px 15px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* hover */\r\n");
      out.write(".products-header select:hover {\r\n");
      out.write("\tborder-color: #3498db;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* focus */\r\n");
      out.write(".products-header select:focus {\r\n");
      out.write("\tborder-color: #3498db;\r\n");
      out.write("\tbox-shadow: 0 0 0 3px rgba(52, 152, 219, 0.2);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ================= FILTER ================= -->\r\n");
      out.write("\t\t<aside class=\"filter\">\r\n");
      out.write("\t\t\t<h3>Thời trang nam</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- LOẠI SẢN PHẨM -->\r\n");
      out.write("\t\t\t<div class=\"filter-group\">\r\n");
      out.write("\t\t\t\t<strong>Loại sản phẩm</strong> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Áo thun\">Áo thun</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Áo sơ mi\">Áo sơ mi</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Áo khoác\">Áo khoác</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Quần jean\">Quần jean</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Quần tây\">Quần tây</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-type\" value=\"Quần short\">Quần short</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- SIZE -->\r\n");
      out.write("\t\t\t<div class=\"filter-group\">\r\n");
      out.write("\t\t\t\t<strong>Kích cỡ</strong> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-size\" value=\"S\">S</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-size\" value=\"M\">M</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-size\" value=\"L\">L</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-size\" value=\"XL\">XL</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-size\" value=\"XXL\">XXL</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- GIÁ -->\r\n");
      out.write("\t\t\t<div class=\"filter-group\">\r\n");
      out.write("\t\t\t\t<strong>Khoảng giá</strong> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-price\" value=\"0-200000\">Dưới 200.000đ</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-price\" value=\"200000-500000\">200.000đ – 500.000đ</label> \r\n");
      out.write("\t\t\t\t<label><input type=\"checkbox\" class=\"filter-price\" value=\"500000-999999999\">Trên 500.000đ</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ================= PRODUCTS ================= -->\r\n");
      out.write("\t\t<section class=\"products\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"products-grid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- PRODUCT -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Hiển thị khi không có sản phẩm -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/user-pages/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tdocument.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\t    // Lấy tất cả checkbox và các card sản phẩm\r\n");
      out.write("\t    const checkboxes = document.querySelectorAll('.filter-group input[type=\"checkbox\"]');\r\n");
      out.write("\t    const products = document.querySelectorAll(\".product-card\");\r\n");
      out.write("\r\n");
      out.write("\t    checkboxes.forEach((checkbox) => {\r\n");
      out.write("\t        checkbox.addEventListener(\"change\", filterProducts);\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("\t    function filterProducts() {\r\n");
      out.write("\t        // Lấy mảng các giá trị được chọn\r\n");
      out.write("\t        const selectedTypes = Array.from(document.querySelectorAll(\".filter-type:checked\")).map(cb => cb.value);\r\n");
      out.write("\t        const selectedSizes = Array.from(document.querySelectorAll(\".filter-size:checked\")).map(cb => cb.value);\r\n");
      out.write("\t        const selectedPrices = Array.from(document.querySelectorAll(\".filter-price:checked\")).map(cb => cb.value);\r\n");
      out.write("\r\n");
      out.write("\t        products.forEach((product) => {\r\n");
      out.write("\t            const pType = product.getAttribute(\"data-type\");\r\n");
      out.write("\t            const pSize = product.getAttribute(\"data-size\");\r\n");
      out.write("\t            const pPrice = parseFloat(product.getAttribute(\"data-price\"));\r\n");
      out.write("\r\n");
      out.write("\t            // Kiểm tra: Nếu không chọn gì ở nhóm đó thì coi như thỏa mãn (Match = true)\r\n");
      out.write("\t            const typeMatch = selectedTypes.length === 0 || selectedTypes.includes(pType);\r\n");
      out.write("\t            const sizeMatch = selectedSizes.length === 0 || selectedSizes.includes(pSize);\r\n");
      out.write("\t            \r\n");
      out.write("\t            let priceMatch = selectedPrices.length === 0;\r\n");
      out.write("\t            selectedPrices.forEach(range => {\r\n");
      out.write("\t                const [min, max] = range.split(\"-\").map(Number);\r\n");
      out.write("\t                if (pPrice >= min && pPrice <= max) priceMatch = true;\r\n");
      out.write("\t            });\r\n");
      out.write("\r\n");
      out.write("\t            // Hiển thị sản phẩm nếu thỏa mãn ĐỒNG THỜI cả 3 bộ lọc\r\n");
      out.write("\t            if (typeMatch && sizeMatch && priceMatch) {\r\n");
      out.write("\t                product.style.display = \"\"; // Để trống để nhận lại giá trị CSS mặc định (grid/block)\r\n");
      out.write("\t            } else {\r\n");
      out.write("\t                product.style.display = \"none\";\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /user-pages/male-clothe.jsp(294,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listP}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/male-clothe.jsp(294,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <div class=\"product-card\" \r\n");
            out.write("                         data-type=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("                         data-size=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("                         data-price=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                        \r\n");
            out.write("                        <div class=\"product-img\">\r\n");
            out.write("                            ");
            out.write("\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/assets/uploaded-images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("                                 alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                            <div class=\"favorite btn-wishlist\" data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t    <i class=\"fa-solid fa-heart\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        \r\n");
            out.write("                        <div class=\"product-info\">\r\n");
            out.write("                            <h4>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("                            <div class=\"price\">\r\n");
            out.write("                                ");
            out.write("\r\n");
            out.write("                                ");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("đ\r\n");
            out.write("                            </div>\r\n");
            out.write("                            <div class=\"btn-group\">\r\n");
            out.write("                               <button class=\"btn btn-cart add-to-cart-btn\" data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t    <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t</button>\r\n");
            out.write("                               <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product-detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-detail\">\r\n");
            out.write("\t\t\t\t\t\t\t\t    Chi tiết\r\n");
            out.write("\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-pages/male-clothe.jsp(313,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /user-pages/male-clothe.jsp(313,32) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /user-pages/male-clothe.jsp(328,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty listP}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <div class=\"text-center w-100 py-5\">\r\n");
          out.write("                        <p class=\"text-muted\">Hiện tại chưa có sản phẩm nào thuộc mục này.</p>\r\n");
          out.write("                    </div>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
